apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/neon-essence-453512-c8/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
        - name: GOOGLE_APPLICATION_CREDENTIALS  # ✅ Set the env variable to point to the mounted file
          value: "/app/config/neon-essence-453512-c8-f61dd8b43f1a.json"
        volumeMounts:
        - name: gcp-credentials
          mountPath: "/app/config"
          readOnly: true
      volumes:
      - name: gcp-credentials
        secret:
          secretName: backend-secrets
          items:
          - key: GOOGLE_APPLICATION_CREDENTIALS
            path: neon-essence-453512-c8-f61dd8b43f1a.json  # ✅ This ensures the JSON file is mounted correctly
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: backend
